/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChorRouteImport } from './routes/chor'
import { Route as SpecialsRouteImport } from './routes/specials'
import { Route as ChorIndexRouteImport } from './routes/chor.index'
import { Route as ChorMixingRouteImport } from './routes/chor.mixing'
import { Route as ChorReportRouteImport } from './routes/chor.report'
import { Route as SpecialsIndexRouteImport } from './routes/specials.index'
import { Route as SpecialsConsistencyRouteImport } from './routes/specials.consistency'
import { Route as SpecialsMixingRouteImport } from './routes/specials.mixing'
import { Route as SpecialsQuantityRouteImport } from './routes/specials.quantity'
import { Route as SpecialsReportRouteImport } from './routes/specials.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChorRoute = ChorRouteImport.update({
  id: '/chor',
  path: '/chor',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsRoute = SpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => rootRouteImport,
} as any)
const ChorIndexRoute = ChorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChorRoute,
} as any)
const ChorMixingRoute = ChorMixingRouteImport.update({
  id: '/mixing',
  path: '/mixing',
  getParentRoute: () => ChorRoute,
} as any)
const ChorReportRoute = ChorReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ChorRoute,
} as any)
const SpecialsIndexRoute = SpecialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecialsRoute,
} as any)
const SpecialsConsistencyRoute = SpecialsConsistencyRouteImport.update({
  id: '/consistency',
  path: '/consistency',
  getParentRoute: () => SpecialsRoute,
} as any)
const SpecialsMixingRoute = SpecialsMixingRouteImport.update({
  id: '/mixing',
  path: '/mixing',
  getParentRoute: () => SpecialsRoute,
} as any)
const SpecialsQuantityRoute = SpecialsQuantityRouteImport.update({
  id: '/quantity',
  path: '/quantity',
  getParentRoute: () => SpecialsRoute,
} as any)
const SpecialsReportRoute = SpecialsReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SpecialsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chor': typeof ChorRouteWithChildren
  '/specials': typeof SpecialsRouteWithChildren
  '/chor/mixing': typeof ChorMixingRoute
  '/chor/report': typeof ChorReportRoute
  '/specials/consistency': typeof SpecialsConsistencyRoute
  '/specials/mixing': typeof SpecialsMixingRoute
  '/specials/quantity': typeof SpecialsQuantityRoute
  '/specials/report': typeof SpecialsReportRoute
  '/chor/': typeof ChorIndexRoute
  '/specials/': typeof SpecialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chor/mixing': typeof ChorMixingRoute
  '/chor/report': typeof ChorReportRoute
  '/specials/consistency': typeof SpecialsConsistencyRoute
  '/specials/mixing': typeof SpecialsMixingRoute
  '/specials/quantity': typeof SpecialsQuantityRoute
  '/specials/report': typeof SpecialsReportRoute
  '/chor': typeof ChorIndexRoute
  '/specials': typeof SpecialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chor': typeof ChorRouteWithChildren
  '/specials': typeof SpecialsRouteWithChildren
  '/chor/mixing': typeof ChorMixingRoute
  '/chor/report': typeof ChorReportRoute
  '/specials/consistency': typeof SpecialsConsistencyRoute
  '/specials/mixing': typeof SpecialsMixingRoute
  '/specials/quantity': typeof SpecialsQuantityRoute
  '/specials/report': typeof SpecialsReportRoute
  '/chor/': typeof ChorIndexRoute
  '/specials/': typeof SpecialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chor'
    | '/specials'
    | '/chor/mixing'
    | '/chor/report'
    | '/specials/consistency'
    | '/specials/mixing'
    | '/specials/quantity'
    | '/specials/report'
    | '/chor/'
    | '/specials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chor/mixing'
    | '/chor/report'
    | '/specials/consistency'
    | '/specials/mixing'
    | '/specials/quantity'
    | '/specials/report'
    | '/chor'
    | '/specials'
  id:
    | '__root__'
    | '/'
    | '/chor'
    | '/specials'
    | '/chor/mixing'
    | '/chor/report'
    | '/specials/consistency'
    | '/specials/mixing'
    | '/specials/quantity'
    | '/specials/report'
    | '/chor/'
    | '/specials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChorRoute: typeof ChorRouteWithChildren
  SpecialsRoute: typeof SpecialsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chor': {
      id: '/chor'
      path: '/chor'
      fullPath: '/chor'
      preLoaderRoute: typeof ChorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specials': {
      id: '/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof SpecialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chor/': {
      id: '/chor/'
      path: '/'
      fullPath: '/chor/'
      preLoaderRoute: typeof ChorIndexRouteImport
      parentRoute: typeof ChorRoute
    }
    '/chor/mixing': {
      id: '/chor/mixing'
      path: '/mixing'
      fullPath: '/chor/mixing'
      preLoaderRoute: typeof ChorMixingRouteImport
      parentRoute: typeof ChorRoute
    }
    '/chor/report': {
      id: '/chor/report'
      path: '/report'
      fullPath: '/chor/report'
      preLoaderRoute: typeof ChorReportRouteImport
      parentRoute: typeof ChorRoute
    }
    '/specials/': {
      id: '/specials/'
      path: '/'
      fullPath: '/specials/'
      preLoaderRoute: typeof SpecialsIndexRouteImport
      parentRoute: typeof SpecialsRoute
    }
    '/specials/consistency': {
      id: '/specials/consistency'
      path: '/consistency'
      fullPath: '/specials/consistency'
      preLoaderRoute: typeof SpecialsConsistencyRouteImport
      parentRoute: typeof SpecialsRoute
    }
    '/specials/mixing': {
      id: '/specials/mixing'
      path: '/mixing'
      fullPath: '/specials/mixing'
      preLoaderRoute: typeof SpecialsMixingRouteImport
      parentRoute: typeof SpecialsRoute
    }
    '/specials/quantity': {
      id: '/specials/quantity'
      path: '/quantity'
      fullPath: '/specials/quantity'
      preLoaderRoute: typeof SpecialsQuantityRouteImport
      parentRoute: typeof SpecialsRoute
    }
    '/specials/report': {
      id: '/specials/report'
      path: '/report'
      fullPath: '/specials/report'
      preLoaderRoute: typeof SpecialsReportRouteImport
      parentRoute: typeof SpecialsRoute
    }
  }
}

interface ChorRouteChildren {
  ChorMixingRoute: typeof ChorMixingRoute
  ChorReportRoute: typeof ChorReportRoute
  ChorIndexRoute: typeof ChorIndexRoute
}

const ChorRouteChildren: ChorRouteChildren = {
  ChorMixingRoute: ChorMixingRoute,
  ChorReportRoute: ChorReportRoute,
  ChorIndexRoute: ChorIndexRoute,
}

const ChorRouteWithChildren = ChorRoute._addFileChildren(ChorRouteChildren)

interface SpecialsRouteChildren {
  SpecialsConsistencyRoute: typeof SpecialsConsistencyRoute
  SpecialsMixingRoute: typeof SpecialsMixingRoute
  SpecialsQuantityRoute: typeof SpecialsQuantityRoute
  SpecialsReportRoute: typeof SpecialsReportRoute
  SpecialsIndexRoute: typeof SpecialsIndexRoute
}

const SpecialsRouteChildren: SpecialsRouteChildren = {
  SpecialsConsistencyRoute: SpecialsConsistencyRoute,
  SpecialsMixingRoute: SpecialsMixingRoute,
  SpecialsQuantityRoute: SpecialsQuantityRoute,
  SpecialsReportRoute: SpecialsReportRoute,
  SpecialsIndexRoute: SpecialsIndexRoute,
}

const SpecialsRouteWithChildren = SpecialsRoute._addFileChildren(
  SpecialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChorRoute: ChorRouteWithChildren,
  SpecialsRoute: SpecialsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
